name: Compila o LaTeX e converte para Word
on: [push]
jobs:
build_latex:
runs-on: ubuntu-latest
steps:
- name: Set up Git repository
uses: actions/checkout@v1
- name: Compile LaTeX document
uses: xu-cheng/latex-action@master
with:
root_file: artigo.tex
convert_via_pandoc:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- run: mkdir output
- uses: docker://pandoc/core:2.9
with:
args: >-
-s artigo.tex
-f latex
-t docx
-o output/comutation-manuscript.docx
--bibliography referencias/referencias.bib
--csl fearp.csl
- uses: actions/upload-artifact@master
with:
name: manuscript
path: output
